#!/usr/bin/env bash
[[ " help webhooks:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in

  help | webhooks:help)
    help_content_func() {
      #shellcheck disable=SC2034
      declare desc="return webhooks plugin help content"
      cat<<help_content
    webhooks <app>, List registered webhooks for an app
    webhooks:listen, Start the webhook server
    webhooks:auto-listen, Automatically keep the webhook server running
    webhooks:stop, Stop the webhook server
    webhooks:secret <app> <secret>, Set the secret for an app
    webhooks:enable <app>, Enable all webhooks for an app
    webhooks:disable <app>, Disable all webhooks for an app
    webhooks:create <app> <name> <command>, Create a webhook
    webhooks:delete <app> <name>, Delete a webhook
    webhooks:trigger <app> <name>, Manually trigger a webhook
    webhooks:logs <app>, Show webhook activation logs for an app
help_content
    }

    if [[ $1 = "webhooks:help" ]]; then
      echo -e 'Usage: dokku webhooks[:COMMAND]'
      echo ''
      echo 'Trigger dokku commands using webhooks.'
      echo ''
      echo 'Additional commands:'
      help_content_func | sort | column -c2 -t -s,
    elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
      help_content_func
    else
      cat<<help_desc
    webhooks, Plugin managing your dokku apps through a web interface
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
